export const PERMISSIONS = {
  SUPER_ADMIN: 'SUPER_ADMINISTRADOR',
  ARCHIVE: {
    UPLOAD: 'SUBIR_ARCHIVOS',
    READ: 'LEER_ARCHIVOS',
  },
  ROLES: {
    READ_BASE: 'LEER_ROLES_BASE',
    READ_COMPOSITE: 'LEER_ROLES_COMPUESTOS',
    READ_ROLE_COMPOSITES: 'LEER_COMPOSITES_ROL',
    CREATE: 'CREAR_ROL',
    UPDATE: 'EDITAR_ROL',
    DELETE: 'ELIMINAR_ROL',
    READ_USERS_BY_ROLE: 'LEER_USUARIOS_POR_ROL',
  },
  USERS: {
    CREATE: 'CREAR_USUARIO',
    READ: 'LEER_USUARIO',
    READ_ALL: 'LEER_USUARIOS',
    READ_ROLES: 'LEER_ROLES_USUARIO',
    APPROVE: 'APROBAR_USUARIO',
    ASSIGN_ROLE: 'ASIGNAR_ROL_USUARIO',
    REMOVE_ROLE: 'ELIMINAR_ROL_USUARIO',
    READ_INVITATIONS: 'LEER_INVITACIONES_PENDIENTES',
  },
  INVENTORY: {
    READ: 'LEER_ACTIVOS',
    MANAGE: 'GESTIONAR_ACTIVOS',
    DELETE: 'ELIMINAR_ACTIVOS',
    CATALOG: {
      READ: 'LEER_ACTIVOS',
      MANAGE: 'GESTIONAR_ACTIVOS',
      DELETE: 'ELIMINAR_ACTIVOS',
    },
    LOCATIONS: {
      READ: 'LEER_UBICACIONES',
      MANAGE: 'GESTIONAR_UBICACIONES',
      DELETE: 'ELIMINAR_UBICACIONES',
    },
  },
};