export const PERMISSIONS = {
  SUPER_ADMIN: 'SUPER_ADMINISTRADOR',
  ARCHIVE: {
    UPLOAD: 'SUBIR_ARCHIVOS',
    READ: 'LEER_ARCHIVOS',
  },
  ROLES: {
    READ_BASE: 'LEER_ROLES_BASE',
    READ_COMPOSITE: 'LEER_ROLES_COMPUESTOS',
    READ_ROLE_COMPOSITES: 'LEER_COMPOSITES_ROL',
    CREATE: 'CREAR_ROL',
    UPDATE: 'EDITAR_ROL',
    DELETE: 'ELIMINAR_ROL',
    READ_USERS_BY_ROLE: 'LEER_USUARIOS_POR_ROL',
  },
  USERS: {
    CREATE: 'CREAR_USUARIO',
    READ: 'LEER_USUARIO',
    READ_ALL: 'LEER_USUARIOS',
    READ_ROLES: 'LEER_ROLES_USUARIO',
    APPROVE: 'APROBAR_USUARIO',
    ASSIGN_ROLE: 'ASIGNAR_ROL_USUARIO',
    REMOVE_ROLE: 'ELIMINAR_ROL_USUARIO',
    READ_INVITATIONS: 'LEER_INVITACIONES_PENDIENTES',
  },
  INVENTORY: {
    READ: 'LEER_ACTIVOS',
    MANAGE: 'GESTIONAR_ACTIVOS',
    DELETE: 'ELIMINAR_ACTIVOS',
    CATALOG: {
      READ: 'LEER_ACTIVOS',
      MANAGE: 'GESTIONAR_ACTIVOS',
      DELETE: 'ELIMINAR_ACTIVOS',
    },
    LOCATIONS: {
      READ: 'LEER_UBICACIONES',
      MANAGE: 'GESTIONAR_UBICACIONES',
      DELETE: 'ELIMINAR_UBICACIONES',
    },
  },
  MAINTENANCE: {
    COMPANIES: {
      READ: 'LEER_EMPRESAS',
      MANAGE: 'GESTIONAR_EMPRESAS',
      DELETE: 'ELIMINAR_EMPRESAS',
    },
    REQUESTS: {
      READ: 'LEER_SOLICITUDES_MANTENIMIENTO',
      REQUEST: 'SOLICITAR_MANTENIMIENTO',
      UPDATE: 'EDITAR_SOLICITUDES_MANTENIMIENTO',
      SELECT_COMPANY: 'SELECCIONAR_EMPRESA_EN_SOLICITUD_MANTENIMIENTO',
      DELETE: 'ELIMINAR_SOLICITUDES_MANTENIMIENTO',
    },
    REGISTERS: {
      READ: 'LEER_REGISTROS_MANTENIMIENTO',
      MANAGE: 'GESTIONAR_REGISTROS_MANTENIMIENTO',
      HISTORY: 'LEER_HISTORIAL_REGISTROS_MANTENIMIENTO',
    },
    COMPANY_USERS: {
      READ: 'LEER_USUARIOS_EMPRESAS',
      MANAGE: 'GESTIONAR_USUARIOS_EMPRESAS',
      DELETE: 'ELIMINAR_USUARIOS_EMPRESAS',
    },
    TICKETS: {
      READ: 'LEER_TICKET_MANTENIMIENTO',
      CREATE: 'CREAR_TICKETS_MANTENIMIENTO',
      EDIT: 'EDITAR_TICKETS_MANTENIMIENTO',
      SET_PRIORITY: 'ASIGNAR_PRIORIDAD_TICKETS_MANTENIMIENTO',
      VIEW_ALL: 'LEER_TODOS_TICKETS_MANTENIMIENTO',
      COMMENT: 'COMENTAR_TICKETS_MANTENIMIENTO',
      DELETE: 'ELIMINAR_TICKETS_MANTENIMIENTO',
    },
  },
};