export const queryKeys = {
    inventory: {
        root: ['inventory'],
        assets: () => [...queryKeys.inventory.root, 'assets'],
        assetList: (params) => [...queryKeys.inventory.assets(), 'list', params],
        assetDetail: (assetId) => [...queryKeys.inventory.assets(), 'detail', assetId],
        assetFullDetail: (assetId) => [...queryKeys.inventory.assets(), 'full-detail', assetId],
        assetComponents: (assetId) => [...queryKeys.inventory.assets(), 'components', assetId],
        assetPhotos: (assetId) => [...queryKeys.inventory.assets(), 'photos', assetId],
        assetMaintenanceHistory: (assetId, params) => [...queryKeys.inventory.assets(), 'maintenance-history', assetId, params],
        catalog: () => [...queryKeys.inventory.root, 'catalog'],
        catalogList: (baseUrl, params) => [...queryKeys.inventory.catalog(), 'list', baseUrl, params],
        catalogOptions: () => [...queryKeys.inventory.catalog(), 'options'],
    },
    locations: {
        root: ['locations'],
        list: (resource, params) => [...queryKeys.locations.root, 'list', resource, params],
        options: (resource) => [...queryKeys.locations.root, 'options', resource],
        emails: () => [...queryKeys.locations.root, 'emails'],
        buildingEmails: (buildingId) => [...queryKeys.locations.emails(), 'building', buildingId],
        campusEmails: (campusId) => [...queryKeys.locations.emails(), 'campus', campusId],
    },
    maintenance: {
        root: ['maintenance'],
        requests: () => [...queryKeys.maintenance.root, 'requests'],
        requestList: (params) => [...queryKeys.maintenance.requests(), 'list', params],
        requestDetail: (requestId) => [...queryKeys.maintenance.requests(), 'detail', requestId],
        requestLocationNames: (campusId, buildingId) => [...queryKeys.maintenance.requests(), 'location-names', campusId, buildingId],
        tickets: () => [...queryKeys.maintenance.root, 'tickets'],
        ticketList: (params) => [...queryKeys.maintenance.tickets(), 'list', params],
        ticketDetail: (ticketId) => [...queryKeys.maintenance.tickets(), 'detail', ticketId],
        ticketHistory: (ticketId) => [...queryKeys.maintenance.tickets(), 'history', ticketId],
        register: () => [...queryKeys.maintenance.root, 'register'],
        registerList: (scope, params) => [...queryKeys.maintenance.register(), 'list', scope, params],
        registerAssets: (registerId, params) => [...queryKeys.maintenance.register(), 'assets', registerId, params],
        assetRecords: (registerId, assetId, params) => [...queryKeys.maintenance.register(), 'asset-records', registerId, assetId, params],
        companies: () => [...queryKeys.maintenance.root, 'companies'],
        companyList: (params) => [...queryKeys.maintenance.companies(), 'list', params],
        companyDetail: (companyId) => [...queryKeys.maintenance.companies(), 'detail', companyId],
        companyUsers: (companyId, params) => [...queryKeys.maintenance.companies(), 'users', companyId, params],
        technicians: (params) => [...queryKeys.maintenance.root, 'technicians', params],
        locationOptions: (resource, parentId) => [...queryKeys.maintenance.root, 'location-options', resource, parentId],
    },
    security: {
        root: ['security'],
        roles: () => [...queryKeys.security.root, 'roles'],
        roleList: (params) => [...queryKeys.security.roles(), 'list', params],
        roleCatalog: (params) => [...queryKeys.security.roles(), 'catalog', params],
        users: () => [...queryKeys.security.root, 'users'],
        userList: (params) => [...queryKeys.security.users(), 'list', params],
        userRoles: (userId) => [...queryKeys.security.users(), 'roles', userId],
        userStatuses: () => [...queryKeys.security.users(), 'statuses'],
        roleForm: (roleName) => [...queryKeys.security.roles(), 'form', roleName],
    },
    transport: {
        root: ['transport'],
        vehicles: () => [...queryKeys.transport.root, 'vehicles'],
        vehicleList: (params) => [...queryKeys.transport.vehicles(), 'list', params],
        vehicleOptions: () => [...queryKeys.transport.vehicles(), 'options'],
        drivers: () => [...queryKeys.transport.root, 'drivers'],
        driverList: (params) => [...queryKeys.transport.drivers(), 'list', params],
        driverOptions: () => [...queryKeys.transport.drivers(), 'options'],
        tours: () => [...queryKeys.transport.root, 'tours'],
        tourList: (params) => [...queryKeys.transport.tours(), 'list', params],
        tourOptions: () => [...queryKeys.transport.tours(), 'options'],
        maintenance: () => [...queryKeys.transport.root, 'maintenance'],
        maintenanceList: (params) => [...queryKeys.transport.maintenance(), 'list', params],
        assignment: () => [...queryKeys.transport.root, 'assignment'],
        assignmentList: (params) => [...queryKeys.transport.assignment(), 'list', params],
        cleaning: () => [...queryKeys.transport.root, 'cleaning'],
        cleaningList: (params) => [...queryKeys.transport.cleaning(), 'list', params],
        cleaningDetail: (cleaningId) => [...queryKeys.transport.cleaning(), 'detail', cleaningId],
    },
};
