spring:
  application:
    name: msvc-gateway
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://msvc-config:8888}

cors:
  allowed-origins: http://localhost:5173,http://localhost:5174

keycloak:
  client-id: sssi-app