spring:
  application:
    name: msvc-gateway
  config:
    import: optional:configserver:http://localhost:8888

cors:
  allowed-origins: http://localhost:5173,http://localhost:5174

keycloak:
  client-id: sssi-app