[privilegios]
ACEPTAR_SOLICITUDES_MANTENIMIENTO
ACTUALIZAR_ASIGNACIONES
APROBAR_USUARIO
ASIGNAR_PRIORIDAD_TICKETS_MANTENIMIENTO
ASIGNAR_ROL_USUARIO
ASIGNAR_TICKETS_MANTENIMIENTO
CANCELAR_SOLICITUDES_MANTENIMIENTO
COMENTAR_TICKETS_MANTENIMIENTO
CREAR_ROL
CREAR_TICKETS_MANTENIMIENTO
CREAR_USUARIO
EDITAR_ROL
EDITAR_SOLICITUDES_MANTENIMIENTO
EDITAR_TICKETS_MANTENIMIENTO
ELIMINAR_ACTIVOS
ELIMINAR_CHOFERES
ELIMINAR_EMPRESAS
ELIMINAR_GIRAS
ELIMINAR_MANTENIMIENTO_VEHICULOS
ELIMINAR_ROL
ELIMINAR_ROL_USUARIO
ELIMINAR_SOLICITUDES_MANTENIMIENTO
ELIMINAR_TECNICOS_MANTENIMIENTO
ELIMINAR_TICKETS_MANTENIMIENTO
ELIMINAR_UBICACIONES
ELIMINAR_USUARIOS_EMPRESAS
ELIMINAR_VEHICULOS
EXPORTAR_ACTIVOS
GENERAR_ASIGNACIONES
GESTIONAR_ACTIVOS
GESTIONAR_CHOFERES
GESTIONAR_EMPRESAS
GESTIONAR_GIRAS
GESTIONAR_MANTENIMIENTO_VEHICULOS
GESTIONAR_REGISTROS_MANTENIMIENTO
GESTIONAR_TECNICOS_MANTENIMIENTO
GESTIONAR_UBICACIONES
GESTIONAR_USUARIOS_EMPRESAS
GESTIONAR_VEHICULOS
IMPORTAR_ACTIVOS
LEER_ACTIVOS
LEER_ARCHIVOS
LEER_CHOFERES
LEER_COMPOSITES_ROL
LEER_EMPRESAS
LEER_GIRAS
LEER_HISTORIAL_REGISTROS_MANTENIMIENTO
LEER_INVITACIONES_PENDIENTES
LEER_MANTENIMIENTO_VEHICULOS
LEER_REGISTROS_MANTENIMIENTO
LEER_ROLES_BASE
LEER_ROLES_COMPUESTOS
LEER_ROLES_USUARIO
LEER_SOLICITUDES_MANTENIMIENTO
LEER_TECNICOS_MANTENIMIENTO
LEER_TICKETS_MANTENIMIENTO
LEER_TICKET_MANTENIMIENTO
LEER_TODOS_TICKETS_MANTENIMIENTO
LEER_UBICACIONES
LEER_USUARIO
LEER_USUARIOS
LEER_USUARIOS_EMPRESAS
LEER_USUARIOS_POR_ROL
LEER_VEHICULOS
SELECCIONAR_EMPRESA_EN_SOLICITUD_MANTENIMIENTO
SOLICITAR_MANTENIMIENTO
SUBIR_ARCHIVOS

[rol SUPER_ADMINISTRADOR]
ACEPTAR_SOLICITUDES_MANTENIMIENTO
ACTUALIZAR_ASIGNACIONES
APROBAR_USUARIO
ASIGNAR_PRIORIDAD_TICKETS_MANTENIMIENTO
ASIGNAR_ROL_USUARIO
ASIGNAR_TICKETS_MANTENIMIENTO
CANCELAR_SOLICITUDES_MANTENIMIENTO
COMENTAR_TICKETS_MANTENIMIENTO
CREAR_ROL
CREAR_TICKETS_MANTENIMIENTO
CREAR_USUARIO
EDITAR_ROL
EDITAR_SOLICITUDES_MANTENIMIENTO
EDITAR_TICKETS_MANTENIMIENTO
ELIMINAR_ACTIVOS
ELIMINAR_CHOFERES
ELIMINAR_EMPRESAS
ELIMINAR_GIRAS
ELIMINAR_MANTENIMIENTO_VEHICULOS
ELIMINAR_ROL
ELIMINAR_ROL_USUARIO
ELIMINAR_SOLICITUDES_MANTENIMIENTO
ELIMINAR_TECNICOS_MANTENIMIENTO
ELIMINAR_TICKETS_MANTENIMIENTO
ELIMINAR_UBICACIONES
ELIMINAR_USUARIOS_EMPRESAS
ELIMINAR_VEHICULOS
EXPORTAR_ACTIVOS
GENERAR_ASIGNACIONES
GESTIONAR_ACTIVOS
GESTIONAR_CHOFERES
GESTIONAR_EMPRESAS
GESTIONAR_GIRAS
GESTIONAR_MANTENIMIENTO_VEHICULOS
GESTIONAR_REGISTROS_MANTENIMIENTO
GESTIONAR_TECNICOS_MANTENIMIENTO
GESTIONAR_UBICACIONES
GESTIONAR_USUARIOS_EMPRESAS
GESTIONAR_VEHICULOS
IMPORTAR_ACTIVOS
LEER_ACTIVOS
LEER_ARCHIVOS
LEER_CHOFERES
LEER_COMPOSITES_ROL
LEER_EMPRESAS
LEER_GIRAS
LEER_HISTORIAL_REGISTROS_MANTENIMIENTO
LEER_INVITACIONES_PENDIENTES
LEER_MANTENIMIENTO_VEHICULOS
LEER_REGISTROS_MANTENIMIENTO
LEER_ROLES_BASE
LEER_ROLES_COMPUESTOS
LEER_ROLES_USUARIO
LEER_SOLICITUDES_MANTENIMIENTO
LEER_TECNICOS_MANTENIMIENTO
LEER_TICKETS_MANTENIMIENTO
LEER_TICKET_MANTENIMIENTO
LEER_TODOS_TICKETS_MANTENIMIENTO
LEER_UBICACIONES
LEER_USUARIO
LEER_USUARIOS
LEER_USUARIOS_EMPRESAS
LEER_USUARIOS_POR_ROL
LEER_VEHICULOS
SELECCIONAR_EMPRESA_EN_SOLICITUD_MANTENIMIENTO
SOLICITAR_MANTENIMIENTO
SUBIR_ARCHIVOS

[servicio msvc-maintenance]
LEER_ACTIVOS
LEER_UBICACIONES
LEER_USUARIO
LEER_USUARIOS
CREAR_USUARIO

[servicio msvc-email]
LEER_USUARIO
LEER_USUARIOS_POR_ROL
LEER_EMPRESAS
