server:
  port: 8097

spring:
  application:
    name: msvc-transport
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:8888}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/proseg-realm}

api:
  prefix: /api/v1/transport

routes:
  transport: ${api.prefix}
  drivers: ${api.prefix}/drivers
  vehicles: ${api.prefix}/vehicles
  vehicle-maintenance: ${api.prefix}/maintenance
  tours: ${api.prefix}/tours
  assignments: ${api.prefix}/assignments
  cleaning: ${api.prefix}/cleaning
  reports: ${api.prefix}/reports