server:
  port: ${SERVER_PORT:8097}

spring:
  application:
    name: msvc-transport
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://msvc-config:8888}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:https://auth.example.com/realms/sssi-realm}

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:msvc-transport}
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://msvc-eureka:8761/eureka/}

api:
  prefix: /api/v1/transport

routes:
  transport: ${api.prefix}
