server:
  port: ${SERVER_PORT:8098}

spring:
  application:
    name: msvc-document-processor
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:https://auth.example.com/realms/proseg-realm}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 12MB
