server:
  port: 8090

spring:
  application:
    name: msvc-auth
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/auth_db
    username: sssi_user
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    database: PostgreSQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# ROUTES

api:
  prefix: /api

routes:
  auth:
    ${api.prefix}/auth

