server:
  port: 8090

spring:
  application:
    name: msvc-auth
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://keycloak:8080/auth/realms/proseg-realm}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2.jwt: DEBUG

api:
  prefix: /api

routes:
  auth: ${api.prefix}/auth
  user: ${api.prefix}/user
  role: ${api.prefix}/role

keycloak:
  server-url: ${KEYCLOAK_SERVER_URL:http://keycloak:8080/auth}
  realm: ${KEYCLOAK_REALM:proseg-realm}
  client:
    id: ${KEYCLOAK_CLIENT_ID:proseg-app}
    secret: ${KEYCLOAK_CLIENT_SECRET:}
  admin:
    username: ${KEYCLOAK_ADMIN_USERNAME:}
    password: ${KEYCLOAK_ADMIN_PASSWORD:}