eureka:
  client:
    register-with-eureka: false

server:
  port: 8081

spring:
  application:
    name: msvc-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:https://auth.devbychris.com/realms/sssi-realm}

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: msvc-auth
          uri: http://localhost:8090
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=0

        - id: gateway-actuator
          uri: http://localhost:8081
          predicates:
            - Path=/actuator/**
          filters:
            - StripPrefix=0

        - id: msvc-email
          uri: http://localhost:9090
          predicates:
            - Path=/api/email/**
          filters:
            - StripPrefix=2
