server:
  port: ${SERVER_PORT:8099}

spring:
  application:
    name: msvc-maintenance
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://msvc-config:8888}
  web:
    resources:
      add-mappings: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/sssi-bd}
    username: ${SPRING_DATASOURCE_USERNAME:change-me}
    password: ${SPRING_DATASOURCE_PASSWORD:change-me}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    hikari:
      maximum-pool-size: ${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE:10}
      minimum-idle: ${SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE:5}
      idle-timeout: ${SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT:30000}
      max-lifetime: ${SPRING_DATASOURCE_HIKARI_MAX_LIFETIME:180000}
      connection-timeout: ${SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT:30000}
      validation-timeout: ${SPRING_DATASOURCE_HIKARI_VALIDATION_TIMEOUT:5000}
      connection-test-query: ${SPRING_DATASOURCE_HIKARI_CONNECTION_TEST_QUERY:SELECT 1}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:msvc-maintenance}
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://msvc-eureka:8761/eureka/}

routes:
  test: ${ROUTES_TEST:/test}
