eureka:
  client:
    register-with-eureka: false

server:
  port: 8081

spring:
  application:
    name: msvc-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:https://auth.devbychris.com/realms/sssi-realm}

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: msvc-auth
          uri: http://localhost:8090
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=0

        - id: msvc-auth-user
          uri: http://localhost:8090
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=0

        - id: msvc-auth-role
          uri: http://localhost:8090
          predicates:
            - Path=/api/role/**
          filters:
            - StripPrefix=0

        - id: gateway-actuator
          uri: http://localhost:8081
          predicates:
            - Path=/actuator/**
          filters:
            - StripPrefix=0

        - id: msvc-email
          uri: http://localhost:9090
          predicates:
            - Path=/api/email/**
          filters:
            - StripPrefix=2

        - id: msvc-inventory-brands
          uri: http://localhost:8095
          predicates:
            - Path=/api/v1/inventory/brands/**
          filters:
            - StripPrefix=0

        - id: msvc-inventory-locations
          uri: http://localhost:8095
          predicates:
            - Path=/api/v1/inventory/locations/**
          filters:
            - StripPrefix=0

        - id: msvc-inventory-sites
          uri: http://localhost:8095
          predicates:
            - Path=/api/v1/inventory/sites/**
          filters:
            - StripPrefix=0

        - id: msvc-inventory-types
          uri: http://localhost:8095
          predicates:
            - Path=/api/v1/inventory/types/**
          filters:
            - StripPrefix=0

        - id: msvc-inventory-models
          uri: http://localhost:8095
          predicates:
            - Path=/api/v1/inventory/models/**
          filters:
            - StripPrefix=0

        - id: msvc-inventory-assets
          uri: http://localhost:8095
          predicates:
            - Path=/api/v1/inventory/assets/**
          filters:
            - StripPrefix=0

        - id: msvc-inventory-network-interfaces
          uri: http://localhost:8095
          predicates:
            - Path=/api/v1/inventory/network-interfaces/**
          filters:
            - StripPrefix=0

        - id: msvc-inventory-asset-archives
          uri: http://localhost:8095
          predicates:
            - Path=/api/v1/inventory/asset-archives,/api/v1/inventory/asset-archives/**
          filters:
            - StripPrefix=0

        - id: msvc-archive
          uri: http://localhost:8096
          predicates:
            - Path=/api/v1/archive/**
          filters:
            - StripPrefix=0