server:
  port: 8095

spring:
  application:
    name: msvc-inventory

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:https://auth.devbychris.com/realms/sssi-realm}

  datasource:
    url: jdbc:postgresql://76.13.124.126:5432/sssi-bd
    username: sssi_user
    password: sssi_user
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 180000
      connection-timeout: 30000
      validation-timeout: 5000
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

api:
  prefix: /api/v1/inventory

routes:
  brands: ${api.prefix}/brands
  locations: ${api.prefix}/locations
  sites: ${api.prefix}/sites
  types: ${api.prefix}/types
  models: ${api.prefix}/models
  assets: ${api.prefix}/assets
  network-interfaces: ${api.prefix}/network-interfaces
  alarm-sensors: ${api.prefix}/assets/alarm-sensors
  images: ${api.prefix}/images