server:
  port: 8098

spring:
  application:
    name: msvc-document-processor
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:https://auth.devbychris.com/realms/sssi-realm}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 12MB

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:msvc-documento-processor}
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://msvc-eureka:8761/eureka}