name: Deploy Proseg

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script_stop: true
          script: |
            cd ${{ secrets.VPS_APP_DIR }}
            git reset --hard HEAD
            git pull origin main

            cd app/sssi-app
            npm install
            npm run build

            cd ../../services
            docker compose --env-file .env.prod.example -f docker-compose.prod.yml up -d --build
            docker image prune -f

            nginx -t
            systemctl reload nginx